const express = require('express')
const db = require('../db')

const router = express.Router()

// export our router to be mounted by the parent application
module.exports = router

// get database time
router.get('/now', async (req, res) => {
  const { rows } = await db.query('SELECT NOW()')
  res.send(rows[0])
})

// get all
router.get('/pnr', async (req, res) => {
  console.log('GET /pnr');
  const { rows } = await db.query('SELECT * FROM bpk')
  res.send(rows)
})

// delete all
router.delete('/pnr', async (req, res) => {
  console.log('DELETE /pnr');
  const { rows } = await db.query('TRUNCATE bpk')
  res.send(rows)
})

// get one
router.get('/pnr/:pnr', async (req, res) => {
  console.log('GET /pnr/:pnr');
  const { pnr } = req.params
  const bpk = req.body.bpk
  const { rows } = await db.query('SELECT * FROM bpk WHERE pnr = $1', [pnr])
  if (rows.length == 0) {
    res.sendStatus(404)
  }
  res.send(rows.slice(-1)[0])
})

// insert new
router.post('/pnr/:pnr', async (req, res) => {
  console.log('POST /pnr/:pnr');
  const { pnr } = req.params
  const bpk = req.body.bpk
  const { id } = await db.query('INSERT INTO bpk(pnr, bpk) VALUES($1, $2) RETURNING id', [pnr, bpk])
  console.log('POST /pnr/:pnr, id: %s', id);
  // read the id field that was generated by the database upon insert and returned as result
  result = {
    "id": id,
    "pnr": pnr,
    "bpk": bpk,
  }
  res.status(201).send(result)
})

// delete all entries with matching pnr
router.delete('/pnr/:pnr', async (req, res) => {
  console.log('DELETE /pnr/:pnr');
  const { pnr } = req.params
  await db.query('DELETE FROM bpk WHERE pnr = $1', [pnr])
  res.sendStatus(200)
})
