const express = require('express')
const db = require('../db')

const router = express.Router()

// export our router to be mounted by the parent application
module.exports = router

router.get('/now', async (req, res) => {
  await db.query('SELECT NOW()')
    .then((qres) => {
      const { rows } = qres
      res.send(rows[0])
    })
    .catch(e => {
      console.log(e)
      res.sendStatus(500)
    })
})

// get all
router.get('/pnr', async (req, res) => {
  console.log('GET /pnr');
  await db.query('SELECT * FROM bpk')
    .then((qres) => {
      const { rows } = qres
      res.send(rows)
    })
    .catch(e => {
      console.log(e)
      res.sendStatus(500)
    })
})

// delete all
router.delete('/pnr', async (req, res) => {
  console.log('DELETE /pnr');
  await db.query('TRUNCATE bpk')
    .then((qres) => {
      const { rows } = qres
      res.send(rows)
    })
    .catch(e => {
      console.log(e)
      res.sendStatus(500)
    })
})

// get one
router.get('/pnr/:pnr', async (req, res) => {
  console.log('GET /pnr/:pnr');
  const { pnr } = req.params
  const bpk = req.body.bpk
  await db.query('SELECT * FROM bpk WHERE pnr = $1', [pnr])
    .then((qres) => {
      const { rows } = qres;
      if (rows.length == 0)  {
        res.sendStatus(404)
      }
      res.send(rows.slice(-1)[0])
    })
    .catch(e => {
      console.log(e)
      res.sendStatus(500)
    })
})

// insert new
router.post('/pnr/:pnr', async (req, res) => {
  console.log('POST /pnr/:pnr');
  const { pnr } = req.params
  const bpk = req.body.bpk
  await db.query('INSERT INTO bpk(pnr, bpk) VALUES($1, $2) RETURNING id', [pnr, bpk])
    .then((qres) => {
      console.log('POST /pnr/:pnr, qres: %s', qres);
      // read the id field that was generated by the database upon insert and returned as result
      const { id } = qres.rows[0];
      result = {
        "id": id,
        "pnr": pnr,
        "bpk": bpk,
      }
      res.status(201).send(result)
    })
    .catch(e => {
      console.log(e)
      res.sendStatus(500)
    })
})

// delete matching
router.delete('/pnr/:pnr', async (req, res) => {
  console.log('DELETE /pnr/:pnr');
  const { pnr } = req.params
  await db.query('DELETE FROM bpk WHERE pnr = $1', [pnr])
    .then((qres) => res.sendStatus(200))
    .catch(e => {
      console.log(e)
      res.sendStatus(500)
    })
})
